apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pong
spec:
  endpoints:
  - interval: 5s
    port: web
    scheme: http
    path: /metrics
  selector:
    matchLabels:
      app: pong
